      SUBROUTINE UHYPER(BI1,BI2,AJ,U,UI1,UI2,UI3,TEMP,NOEL,
     1            CMNAME,INCMPFLAG,NUMSTATEV,STATEV,NUMFIELDV,FIELDV,
     2             FIELDVINC,NUMPROPS,PROPS)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME
      DIMENSION U(2),UI1(3),UI2(6),UI3(6),STATEV(*),FIELDV(*),
     1              FIELDVINC(*),PROPS(*)
      
      PARAMETER (ZERO=0.0D0,ONE=1.0D0, TWO=2.0D0, THREE=3.0D0,
     1           FOUR=4.0D0, EIGHT=8.0D0 ,NINE=9.0D0  )
C      
      C10 = PROPS(1)
      C01 = PROPS(2)
      D1 = PROPS(3)
       
      U=C10*(BI1-THREE)+C01*(BI2-THREE)+((AJ-ONE)**(2))/D1
      
      UI1(1) = C10
      UI1(2) = C01
      UI1(3) = TWO*(AJ-ONE)/D1
      UI2(1)=ZERO
      UI2(2)=ZERO
      UI2(3)=TWO/D1
      UI2(4)=ZERO
      UI2(5)=ZERO
      UI2(6)=ZERO
      UI3(1)=ZERO
      UI3(2)=ZERO
      UI3(3)=ZERO
      UI3(4)=ZERO
      UI3(5)=ZERO
      UI3(6)=ZERO
      RETURN
      END
      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,TRBARS,KSLAY,KSTEP,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERL,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*8 MATERL
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      DIMENSION BBARSQ(6),BBAR(6),BBARP(3),BBARN(3),DISTGR(3,3)

      PARAMETER(ZERO=0.D0, ONE=1.D0, TWO=2.D0, THREE=3.D0, FOUR=4.D0,
     1 FIVE=5.D0,SIX=6.D0)
C
C ----------------------------------------------------------------
C
C ELASTIC PROPERTIES
C
      C10=PROPS(1)
      C01=PROPS(2)
      D1 = PROPS(3)

C
C JACOBIAN AND DISTORTION TENSOR
C


      SCALE=AJ**(-ONE/THREE)
      DO K1=1, 3
        DO K2=1, 3
          DISTGR(K2, K1)=SCALE*DFGRD1(K2, K1)
        END DO
      END DO
C CALCULATE DEVIATORIC LEFT CAUCHY-GREEN DEFORMATION TENSOR
C
      BBAR(1)=DISTGR(1, 1)**2+DISTGR(1, 2)**2+DISTGR(1, 3)**2
      BBAR(2)=DISTGR(2, 1)**2+DISTGR(2, 2)**2+DISTGR(2, 3)**2
      BBAR(3)=DISTGR(3, 3)**2+DISTGR(3, 1)**2+DISTGR(3, 2)**2
      BBAR(4)=DISTGR(1, 1)*DISTGR(2, 1)+DISTGR(1, 2)*DISTGR(2, 2)
     1 +DISTGR(1, 3)*DISTGR(2, 3)
      IF(NSHR.EQ.3) THEN
        BBAR(5)=DISTGR(1, 1)*DISTGR(3, 1)+DISTGR(1, 2)*DISTGR(3, 2)
     1 +DISTGR(1, 3)*DISTGR(3, 3)
        BBAR(6)=DISTGR(2, 1)*DISTGR(3, 1)+DISTGR(2, 2)*DISTGR(3, 2)
     1 +DISTGR(2, 3)*DISTGR(3, 3)
      END IF
      
      BBARSQ(1)=BBAR(1)**2+BBAR(4)**2+BBAR(5)**2
      BBARSQ(2)=BBAR(2)**2+BBAR(4)**2+BBAR(6)**2
      BBARSQ(3)=BBAR(3)**2+BBAR(5)**2+BBAR(6)**2
      BBARSQ(4)=BBAR(1)*BBAR(4)+BBAR(4)*BBAR(2)+BBAR(5)*BBAR(6)
      IF(NSHR.EQ.3) THEN
        BBARSQ(5)=BBAR(1)*BBAR(5)+BBAR(4)*BBAR(6)+BBAR(5)*BBAR(3)
        BBARSQ(6)=BBAR(4)*BBAR(5)+BBAR(2)*BBAR(6)+BBAR(6)*BBAR(3)
      END IF
C
C CALCULATE THE STRESS
C
C TRACE OF BBARS^2 TRBARS      
      TRBARS=(BBARSQ(1)+BBARSQ(2)+BBARSQ(3))
C TRACE OF BBAR TRBBAR      
      TRBBAR=(BBAR(1)+BBAR(2)+BBAR(3))
C SECOND INVARIANT OF BBAR TRBBARS      
      TRBBARS=(TRBBAR**(TWO)-TRBARS)/TWO
      EA=TWO*C10/AJ
      EB=TWO*C01/AJ
      EC=TWO/D1
            
      DO K1=1,NDI
        STRESS(K1)=(EA+EB*TRBBAR)*BBAR(K1)-EB*BBARSQ(K1)+EC*(AJ-ONE)
     1     -EA*TRBBAR/THREE+TWO*EB*TRBARS/THREE
     
      END DO 
      DO K1=NDI+1,NDI+NSHR
        STRESS(K1)=(EA+EB*TRBBAR)*BBAR(K1)-EB*BBARSQ(K1)
      END DO
C CALCULATE THE STIFFNESS
C
      MUA=TWO*C10
      MUB=TWP*C01
      COEFA=MUA+TWO*MUB*TRBBAR
      COEFB=MUA*TRBBAR+FOUR*MUB*TRBBARS
      COEFC=MUA*TRBBAR+TWO*MUB*TRBBARS
      AK=TWO*D1
      EA=DET*(TWO*DET-ONE)
      DDSDDE(1, 1)= AK*DET-(FOUR/THREE)*BBAR(1)*(COEFA)+EIGHT/THREE*MUB
     1    *BBAR(1)**2+TWO/NINE*(COEFB)+TWO/THREE*COEFC
      DDSDDE(2, 2)= AK*DET-(FOUR/THREE)*BBAR(2)*(COEFA)+EIGHT/THREE*MUB
     1    *BBAR(2)**2+TWO/NINE*(COEFB)+TWO/THREE*COEFC
      DDSDDE(3, 3)= AK*DET-(FOUR/THREE)*BBAR(3)*(COEFA)+EIGHT/THREE*MUB
     1    *BBAR(3)**2+TWO/NINE*(COEFB)+TWO/THREE*COEFC
      DDSDDE(1, 2)=AK*(EA)+TWO*MUB*(BBAR(1)*BBAR(2)-BBAR(4)**2)
     1 -TWO/THREE*(COEFA)*(BBAR(1)+BBAR(2))+FOUR/THREE*MUB*(BBAR(1)**2
     2 +BBAR(2)**2)+TWO/NINE*(COEFB) 
      DDSDDE(1, 3)=AK*(EA)+TWO*MUB*(BBAR(1)*BBAR(3)-BBAR(5)**2)
     1 -TWO/THREE*(COEFA)*(BBAR(1)+BBAR(2))+FOUR/THREE*MUB*(BBAR(1)**2
     2 +BBAR(2)**2)+TWO/NINE*(COEFB) 
      DDSDDE(1, 4)=-TWO/THREE*COEFA*BBAR(4)+FOUR/THREE*MUB*BBAR(4)**2
      DDSDDE(2, 3)=AK*EA+TWO*MUB*(BBAR(2)*BBAR(3)-BBAR(6))-TWO/THREE
     1 *COEFA*(BBAR(2)+BBAR(3))+FOUR/THREE*MUB*(BBAR(2)**2+BBAR(3)**2)
     2 +TWO/NINE*(COEFB)
      DDSDDE(2, 4)= -TWO/THREE*COEFA*BBAR(4)+FOUR/THREE*MUB*BBAR(4)**2
      DDSDDE(3, 4)=TWO*MUB*(BBAR(3)*BBAR(6)-BBAR(5)*BBAR(6))-TWO/THREE
     1 *COEFA*BBAR(4)-FOUR/THREE*MUB*BBAR(4)**2
      DDSDDE(3, 5)=TWO*MUB*(COEFA)*BBAR(5)-FOUR/THREE*MUB*BBAR(5)**2
      DDSDDE(4, 4)= AK*(DET-DET**2)+TWO*MUB*(BBAR(4)**2-(BBAR(1)*BBAR(2)
     1   +BBAR(4)**2)/TWO)+ONE/THREE*COEFC
      IF(NSHR.EQ.3) THEN
        DDSDDE(1, 5)=-TWO/THREE*COEFA*BBAR(5)+FOUR/THREE*MUB*BBAR(5)**2 
        DDSDDE(1, 6)=-TWO/THREE*COEFA*BBAR(6)+FOUR/THREE*MUB*BBAR(6)**2
        DDSDDE(2, 5)=TWO*MUB*(BBAR(2)*BBAR(5)-BBAR(4)*BBAR(6))-TWO/THREE
     1   *COEFA*BBAR(5)+FOUR/THREE*MUB*BBAR(5)**2
        DDSDDE(2, 6)= -TWO/THREE*COEFA*BBAR(6)+FOUR/THREE*MUB*BBAR(6)**2
        DDSDDE(3, 6)=TWO*MUB*(COEFA)*BBAR(6)-FOUR/THREE*MUB*BBAR(6)**2
        DDSDDE(4,5)= TWO*MUB*(BBAR(4)*BBAR(5)-(BBAR(1)*BBAR(6)+BBAR(5)
     1   *BBAR(4))/TWO)       
        DDSDDE(4,6)= TWO*MUB*(BBAR(4)*BBAR(6)-(BBAR(4)*BBAR(6)+BBAR(5)
     1   *BBAR(2))/TWO) 
        DDSDDE(5,5)=AK*(-DET*(DET-ONE))+TWO*MUB*(BBAR(5)*BBAR(5)
     1   -(BBAR(1)*BBAR(3)+BBAR(5)*BBAR(6))/TWO)+ONE/THREE*COEFC
        DDSDDE(5,6)= TWO*MUB*(BBAR(5)*BBAR(6)-(BBAR(4)*BBAR(3)+BBAR(5)
     1   *BBAR(6))/TWO) 
        DDSDDE(6,6)=AK*(-DET*(DET-ONE))+TWO*MUB*(BBAR(6)*BBAR(6)
     1   -(BBAR(2)*BBAR(3)+BBAR(6)*BBAR(6))/TWO)+ONE/THREE*COEFC

      END IF
      DO K1=1, NTENS
        DO K2=1, K1-1
           DDSDDE(K1, K2)=DDSDDE(K2, K1)
        END DO
      END DO
      
C CALCULATE LOGARITHMIC ELASTIC STRAINS (OPTIONAL)
C
      
C
      RETURN
      END
